// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLY3wgIVNxaICFY8IRfDqiOVULKz6zseQ',
    appId: '1:1048548279774:web:de9236951aa39b0aa2c94f',
    messagingSenderId: '1048548279774',
    projectId: 'okulsistemi-80243',
    authDomain: 'okulsistemi-80243.firebaseapp.com',
    databaseURL: 'https://okulsistemi-80243-default-rtdb.firebaseio.com',
    storageBucket: 'okulsistemi-80243.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiYiGp9Shdn0JRXDWBj1Lq_TGzNRI_7eE',
    appId: '1:1048548279774:android:50ad6dbe7b1222e5a2c94f',
    messagingSenderId: '1048548279774',
    projectId: 'okulsistemi-80243',
    databaseURL: 'https://okulsistemi-80243-default-rtdb.firebaseio.com',
    storageBucket: 'okulsistemi-80243.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv2L65LTyMKlpW9_uhKcoZgtNKhaZEFUY',
    appId: '1:1048548279774:ios:b2781cb7979c3ddba2c94f',
    messagingSenderId: '1048548279774',
    projectId: 'okulsistemi-80243',
    databaseURL: 'https://okulsistemi-80243-default-rtdb.firebaseio.com',
    storageBucket: 'okulsistemi-80243.firebasestorage.app',
    iosClientId: '1048548279774-5g288lba98ngdoek0c1fl6bpqmkf1umb.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitirmeProjesi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv2L65LTyMKlpW9_uhKcoZgtNKhaZEFUY',
    appId: '1:1048548279774:ios:b2781cb7979c3ddba2c94f',
    messagingSenderId: '1048548279774',
    projectId: 'okulsistemi-80243',
    databaseURL: 'https://okulsistemi-80243-default-rtdb.firebaseio.com',
    storageBucket: 'okulsistemi-80243.firebasestorage.app',
    iosClientId: '1048548279774-5g288lba98ngdoek0c1fl6bpqmkf1umb.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitirmeProjesi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLY3wgIVNxaICFY8IRfDqiOVULKz6zseQ',
    appId: '1:1048548279774:web:73369c1020009b6aa2c94f',
    messagingSenderId: '1048548279774',
    projectId: 'okulsistemi-80243',
    authDomain: 'okulsistemi-80243.firebaseapp.com',
    databaseURL: 'https://okulsistemi-80243-default-rtdb.firebaseio.com',
    storageBucket: 'okulsistemi-80243.firebasestorage.app',
  );
}
